### ISSUE TITLE
`raku.includePaths` doesn't seem to work

### ISSUE THREAD

**Issue by gdonald** [bscan/RakuNavigator#12]
In my `settings.json` I have added the full path to my `lib` directory in my Raku module: 

```
"raku.includePaths": [
    "/Users/gd/workspace/raku/Console-Blackjack/lib"
]
```

But my code does not then find anything in my `lib` directory:

<img width="689" alt="Screen Shot 2022-06-02 at 7 03 43 PM" src="https://user-images.githubusercontent.com/42317655/171759728-3895f868-728e-47fa-9bd5-4440438ee608.png">

The path I defined in `settings.json` doesn't appear in the list of paths it's searching.  Any idea?  Thanks.

**Comment by bscan** [comment]
Thanks! I needed to fix the order of the raku arguments (i.e. raku -I $path $file instead of raku $file -I $path). I also tested that the include paths work using $workspaceFolder as a variable (if you are using a workspace). Now fixed and available in version 0.1.0.

Thank you for the bug report. The navigator is new and still has some bugs to shake out. More bug reports and suggestions are certainly welcomed.
