### ISSUE TITLE
Syntax: Unrecognized character name [ENTER MARK]

### ISSUE THREAD

**Issue by heyajulia** [bscan/RakuNavigator#2]
Thanks for building this!

The following code:

```raku
say "\c[CHECK MARK]";
```

results in an error:

```
Syntax: Unrecognized character name [ENTER MARK]
raku navigator
```

`CHECK` and `ENTER` are also [phasers](https://docs.raku.org/language/phasers), so maybe that's where it gets confused?

**Comment by bscan** [comment]
Thanks for the report! The original parsing code I borrowed from https://github.com/Raku/Raku-Parser/blob/master/lib/Perl6/Parser.pm6 which tried to remove BEGIN and CHECK blocks for safer compilation (otherwise raku -c and similar compilation methods run those phasers). Although a good idea, it appears to cause a number of issues. Looking around, the other solutions I found seems to simply compile the code without modification (e.g. flycheck-raku, all the perl language servers). Removing those code modifications for now until a more robust method is found.
